### ISSUE TITLE
Issue in detect_event function

### ISSUE THREAD

**Issue by SaswatD** [robwschlegel/heatwaveR#14]
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘"function"’ to a data.frame
In addition: Warning message:
In names(ts_res)[2] <- paste(substitute(x)) :
  number of items to replace is not a multiple of replacement length

Sample code : library(heatwaveR)
library(dplyr)
library(ggpubr)
library(lubridate)
library(readxl)
kara <- read_excel("kara.xlsx")
as.Date(kara$t)

tMax_clim <- ts2clm(kara,x=as.Date(kara$t) ,y = tMax, climatologyPeriod = c("1971-01-01", "2000-12-31"), pctile = 90)
tMin_exc <- exceedance( kara, y = tMin, threshold = 35, minDuration = 3, maxGap = 1)$threshold
events <- detect_event(tMax_clim, y = tMax, 
                       threshClim2 = tMin_exc$exceedance)

**Comment by robwschlegel** [comment]
Hello,
It is unclear from your post which line of your code is generating the error message at the beginning of your post. And without providing a [reprex](https://reprex.tidyverse.org/) I can't say exactly what the issue may be. Looking at the code however I assume it is this line `tMax_clim <- ts2clm(kara,x=as.Date(kara$t) ,y = tMax, climatologyPeriod = c("1971-01-01", "2000-12-31"), pctile = 90)`. Specifically `x=as.Date(kara$t)`. This is because the columns that are passed to the heatwaveR functions must be real columns, not functions acting on those columns. Please try the following code and let me know if it solves this error:

```r
library(dplyr)
library(ggpubr)
library(lubridate)
library(readxl)
kara <- read_excel("kara.xlsx")
kara$t <- as.Date(kara$t)

tMax_clim <- ts2clm(kara, y = tMax, climatologyPeriod = c("1971-01-01", "2000-12-31"), pctile = 90)
tMin_exc <- exceedance(kara, y = tMin, threshold = 35, minDuration = 3, maxGap = 1)$threshold
events <- detect_event(tMax_clim, y = tMax, threshClim2 = tMin_exc$exceedance)
```
All the best,
-Robert

**Comment by SaswatD** [comment]
Hello,
I fixed the above issue, but i got one other query.
How can we use a "departure" from normal approach in the detecting of heat
wave? Can you help.with the code?

Saswat Dash

**Comment by robwschlegel** [comment]
Hello,
I'm not sure I understand what you mean. Can you provide an example? If you mean that you want to find the exceedance above a given threshold, then the `exceedance()` function will do that for you.
In this forum I can only provide assistance with errors in the source code for __`heatwaveR`__. I cannot consult on the creation of code for applied use.
All the best,
-Robert

**Comment by SaswatD** [comment]
Yes , but the threshold needs to be the climatological normal

Saswat Dash

**Comment by robwschlegel** [comment]
One can provide any arbitrary threshold to the `exceedance()` function. Or one can create an artificial threshold and pass that to the `detect_event()` function.
