### ISSUE TITLE
fixed vs moving baseline climatology

### ISSUE THREAD

**Issue by chrisdane** [robwschlegel/heatwaveR#22]
Hi Rob

I have a question (not really an issue): is there already a branch of the heatwaveR package that enables to calculate MHW/MCS based on a moving baseline climatology in contrast to the currently implemented `climatologyPeriod` argument for a fixed baseline climatology?

In [Oliver et al. 2021 (Fig. 8)](https://www.annualreviews.org/doi/abs/10.1146/annurev-marine-032720-095144) you and your colleagues show that using a moving baseline climatology yields significantly different results compared to the fixed baseline climatology.

Thanks a lot and cheers,
Chris

**Comment by robwschlegel** [comment]
Hello Chris,

Thanks for your inquiry. The short answer is that there are currently no plans to implement a moving baseline climatology in the heatwaveR package. In fact I don't think this is possible to do in any of the languages (e.g. python, MATLAB) that have implementations of the Hobday methodology.

The argument for moving vs fixed baselines has it's origins in a deep philosophical divide on how one should define extreme events with reference to a climatic state. I've not been convinced that MHW/MCS should be defined via a moving baseline, so I don't intend to add that to this package.

If you do want to detect events with a moving baseline, this is still possible to do with heatwaveR in a couple of ways. The most straightforward would be to first detrend your temperature time series by removing the long-term linear warming signal. For example, by fitting a linear model to your time series. This would remove the warming signal from the data so that the climatology period chosen would be much less important. This approach would address most of the issues that opponents of the fixed baseline have.

The other option open to you would be to detect MHW/MCS multiple times with multiple different fixed baselines. And from those results to compile the events detected per year around which the given climatology was centred. I won't go into too much detail on this approach because it potentially creates more issues than it solves. I also won't go into the criticisms of one methodology over the other here as that is an interminable debate that I think most researchers in this space no longer expect to find a mutually satisfactory conclusion to. Both arguments have their own valid logical support so it ultimately ends up being an issue of what one's question is and why one is investigating it.

Perhaps not the answer you were looking for, but an honest answer at least.

All the best,
-Robert

**Comment by chrisdane** [comment]
Thanks a lot for your answer. I agree to all points (maybe except that maybe we would gain more insight if the moving baseline would be implemented :P).

Cheers,
Chris
