### ISSUE TITLE
Overlapping heatwave events

### ISSUE THREAD

**Issue by marinamega** [robwschlegel/heatwaveR#28]
Hello, I'm using the heatwave package for in situ temperature from intertidal environment loggers. I have hourly data, so I have several temp values for each date. When I tried to use these data, the output from detect_event function gave me overlapping heatwave events. For example: 
![overlapping events](https://user-images.githubusercontent.com/99750496/223449275-aad59337-aac2-4320-b839-83c0dac47a4d.PNG)

My question is: Can I use the hourly data somehow or I have to use the mean, max or min temp for each day?

Thank you

**Comment by robwschlegel** [comment]
Hello,
The heatwaveR package (indeed the Hobday definition for marine heatwaves) only works with daily data. Unfortunately due to a chunk in the source code of this package it is not possible to provide a sub-daily resolution of data. My advice is to take the daily mean of your hourly temperature data and run that through the heatwaveR code. This then will provide an output that matches the body of literature on marine heatwaves.
All the best,
-Robert

**Comment by marinamega** [comment]
Ok, thank you so much
All the best,
-Marina
