### ISSUE TITLE
Error on running 'detect' function

### ISSUE THREAD

**Issue by geografif** [robwschlegel/heatwaveR#36]
I tried to run detect fuction based on the dataset provided in _test.R.

data <- detect(ts_dat, x = datetime, y = temperature, climatology_start = 1982, climatology_end = 2014)

Despite putting the right year, I got the following error: 

Error in detect(ts_dat, x = datetime, y = temperature, climatology_start = 1982,  : 
  The specified start date precedes the first day of series, which is 1982-01-01

Same thing happened when I tried my own dataset. Any clue what's going on?

**Comment by robwschlegel** [comment]
Hell Afif,
I'm not sure what file you are referring to. To my knowledge there is no script called `_test.R` in the `heatwaveR` package. Likewise, there is no `detect()` function in the package.
For a step by step tutorial for how to detect MHWs using `heatwaveR`, please see this vignette: 
https://robwschlegel.github.io/heatwaveR/articles/detection_and_visualisation.html

In brief, the issues you are encountering are because you must first use `ts2clm()`, and then when you use `detect_event()` you must use date values (e.g. "1982-01-01'", not integer year values like 1982).
```
library(heatwaveR)
df_clim <- ts2clm(sst_WA, climatologyPeriod = c("1982-01-01", "2011-12-31"))
mhw <- detect_event(df_clim)
```

**Comment by geografif** [comment]
Thanks!
Is there any idea how to resolve the following error when running event_line()?

*Error in element_rect(colour = "black", fill = NA, linewidth = 0.75) : 
  unused argument (linewidth = 0.75)*

**Comment by robwschlegel** [comment]
Can you please provide a full example of the code you are running?

**Comment by geografif** [comment]
Sure. I used the provided data.

```
version
rm(list = ls())

getwd()

setwd("D:/cpo")
getwd()

library(ncdf4)
library(tidyverse)
library(terra)
library(dplyr)
library(heatwaveR)
library(heatwave3)

ts <- ts2clm(sst_WA, climatologyPeriod = c("1983-01-01", "2012-12-31"))
res <- detect_event(ts)

event_line(res, spread = 100, start_date = "2010-12-01",
           end_date = "2011-06-30", category = TRUE)
```

It returned the following error:
![error_event-line](https://github.com/robwschlegel/heatwaveR/assets/48111760/32e958ec-18b1-4b01-a012-9670b860107f)

**Comment by robwschlegel** [comment]
This code does not create an error on my computer.
Please update all of your packages and see if that fixes the issue.

**Comment by geografif** [comment]
Hi, it was solved by updating the ggplot2 package. Thank you for your suggestion.
