### ISSUE TITLE
units of extreme event cumulative intensity? 

### ISSUE THREAD

**Issue by chrisdane** [robwschlegel/heatwaveR#41]
Hi Rob

According to the description of `detect_event`, the cumulative intensity (CI) of extreme events shall have units degC days (in case of temperature).

In `detect_event.R` (and `detect_event3.R` that is used by the heatwave3 package) the CI is obtained as
```r
mhw_rel_seas = events_clim$ts_y - events_clim$ts_seas,
intensity_cumulative = sum(mhw_rel_seas),
```
(analogous for the `_relThresh` approach). 

As far as I understand, the units of `mhw_rel_seas` are degC and thus the units of `intensity_cumulative` are degC as well? Transforming these units to degC days would require to calculate the temporal integral of `mhw_rel_seas` over the event duration (since dt = length of a day is constant that would yield a simple multiplication with the duration (in days) of the extreme event), is that correct?

Thanks and kind regards,
Chris

**Comment by robwschlegel** [comment]
Hello Chris,
I'm not sure I fully understand your question.
Please refer to the original Hobday et al. (2016) publication for the full documentation: https://www.sciencedirect.com/science/article/pii/S0079661116000057
In Section 2.1 i_cum is first defined as "cumulative intensity (i_cum) is the integral of intensity over the duration of the event".
In Table 2, where the metrics are defined more specifically, "icum: sum of daily intensity anomalies. Note that the integral omits te which is below the T90 threshold"
The cumulative intensity is the sum of the temperature anomalies, as you've pointed out in the code snippet in your post. It is expressed in units of deg C days to make it more clear to users (outside of those that work with differential equations etc. e.g. physical oceanographers) that it is not simply an amount of temperature, but rather temperature over a period of time. Adding up the daily anomalies is nearly the same as taking the integral over time.
This does however create some artifacts between the statistics and any plots of these values. Take the first plot in this [vignette](https://robwschlegel.github.io/heatwaveR/articles/detection_and_visualisation.html) for example. While the start and end of the event may be on exact date values, the corners of all of the plotted events smoothly meet the climatology lines. In reality, because these are daily sums, and not an integral, the little tails at the end of each event are often not included in the overall i_cum.
I was not on the original paper, so I don't know why this choice was made, but I've always assumed it was made in order to provide a more practical definition for a wider user base and to create a muuuuuuch easier implementation of the code. Imagine the difference in the speed that code would take to calculate integrals for each individual event vs simply summing the anomalies.
If you are interested in digging deeper into the code base, there is a calculation of the integral of the events in the [geom_flame](https://robwschlegel.github.io/heatwaveR/reference/geom_flame.html) plotting function.
Does that approximately answer your question?
All the best,
-Rob

**Comment by chrisdane** [comment]
Hi Rob

Thanks for your reply. In the Hobday paper, the cumulative intensity is defined as
```
i_cum = \int_{t_s}^t_{e-1} (T(t) - T_m(j)) dt
```
for `t_s \lt t \lt t_e` and `j(t_s) \lt j \lt j(t_e)`. Using this definition I understand that `i_cum` has units °C days.

To that you write
> Adding up the daily anomalies is nearly the same as taking the integral over time.

Since `dt` is constant (e.g. a day), I agree that sum and integral over time are "nearly the same"; they simply differ by either multiplying the sum by `dt` (here the duration of an individual extreme event) or not.

However, they do differ, and if I would like to compare MHW results I would get completely different numbers depending on whether this multiplication was done or not. Following Hobday, in my view, would require to multiply with `dt`. Here, however, that is not done, which is why I am still irritated.

Thanks for your help!
Chris

**Comment by robwschlegel** [comment]
Hello Chris,
The code is intentionally written as it is. It is not an error. So then I would advise that, if you are writing your own algorithm, that you ensure that the results match closely to any of the existing Hobday based libraries (e.g. Python, R, MATLAB). Or you are of course free to go off and create and use your own numeric definition as you see fit. Thomas Frölichers lab for example uses a different numerical approach than Hobday. 
In the Hobday definition, one does not multiply the sum of the anomalies by the duration of the event. I think we must be having some sort of communication issue because that makes no sense to me to do. The days in the units come from the sum of the anomalies per day, not via multiplication. Multiplying the sum of the anomalies by the duration of the event would incorrectly amplify the thermal anomaly.
All the best,
-Rob
