### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by khaors** [robwschlegel/heatwaveR#7]
Hi Rob. It has been a pleasure to review your R package. Really Good work.  During the review I have found the following minor issues:

- The release version 0.3.0 does not match the GitHub release 0.2.7. Can you check this?
- I didn't see any section in the README file with guidelines to third parties wishing to contribute to your R package. It would be great if you include a badge to invite people to contribute to the development of heatwaveR. 
- In the README file, you include a really great description of the functionality of heatwaveR and how to use it in a simple example. However, it would be great if these items are included in a separate vignette titled "Introduction to heatwaveR package" or something like that. My point here is that this information about the package and the simple example are available only in the GitHub repository but not inside R when the package is installed. This will free some space in your README to include the contribution badge and to highlight your contact information to report bugs.
- When the R package is installed, the title of the complex_clims vignette is not visible in the _Vignettes and other documentation_ section in the package documentation. Can you check this?

**Comment by robwschlegel** [comment]
Hello,
Apologies for the delay. I've gone over the suggested edits and have my responses itemised below:

- You must have checked the package just as the CRAN version was still being updated to 0.3.0. While this review process was happening my co-author fixed a couple of bugs and so now the version has gone up to 0.3.3. This is the version presently on GitHub. I submitted the source package of 0.3.3 to CRAN today and so it should be reflected there within a week or so.
- In the README file I have now added a section at the end that provides a link with instruction for how to contribute to the package.
- I've taken much of the information on calculating heatwaves and visualising them out of the README and added a few new vignettes that now contain that information.
- I assume that the complex_clims vignette didn't show up in the package because it was not in the version on CRAN when the review occurred. Once the version on CRAN is updated to 0.3.3 this should be resolved.

All the best,
-Robert
